# @author: adibarra (Alec Ibarra)
# @description: Dockerfile to build and run server

FROM python:alpine

WORKDIR /app
COPY /packages/server/ .
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 3000
CMD ["python", "/app/src/main.py", "--production"]
