FROM node:alpine as build_client

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

WORKDIR /app
COPY . .

RUN corepack enable
RUN pnpm install --frozen-lockfile --ignore-scripts
RUN pnpm run build:ci

FROM scratch as client

COPY --from=build_client /app/packages/client/dist /public
