/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Logo: typeof import('./components/Logo.vue')['default']
    NavBar: typeof import('./components/layout/NavBar.vue')['default']
    Provider: typeof import('./components/helper/Provider.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/layout/SideBar.vue')['default']
  }
}
