---
name: Build and Deploy Images

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-and-deploy-images:
    name: 🚀 Build and Deploy Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push client image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.client
          push: true
          tags: ghcr.io/${{ GITHUB.repository }}:client-latest

      - name: Build and push server image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.server
          push: true
          tags: ghcr.io/${{ GITHUB.repository }}:server-latest
