---
name: Pull Request Labeler

on:
  pull_request_target:
    types: [opened]

jobs:
  pr-labeler:
    name: 🏷️ Label PRs
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Run pr-labeler
        uses: actions/labeler@v4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/labeler.yml
          sync-labels: ''
